version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Seoul"
    labels:
      - "dependencies"
      - "actions"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Seoul"
    labels:
      - "docker-dependencies"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Seoul"
    labels:
      - "go-dependencies"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Seoul"
    labels:
      - "terraform-dependencies"