# Test with custom resource limits and security settings
# Validates resource configuration and security context

replicaCount: 1
revisionHistoryLimit: 3

serviceAccount:
  create: true
  automountServiceAccountToken: false

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

rebooter:
  checkIntervalSeconds: 120
  failureThreshold: 5
  dryRun: true
  logFormat: pretty
  logLevel: warn

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 32Mi
