version: '3'
services:
  worker:
    build:
      context: .
    hostname: tfworker
    container_name: tfworker
    restart: unless-stopped
    volumes:
      # <YOUR_GIT_ABSOLUTE_PATH> 값을
      # 로컬에 존재하는 terraform repository 경로로
      # 변경합니다.
      - "<YOUR_GIT_ABSOLUTE_PATH>:/mnt/git"

      # AWS CLI
      # 로컬에 존재하는 AWS CLI 설정파일을 복사합니다.
      - "~/.aws:/root/.aws"

      # Source git in terraform code
      # 로컬에 존재하는 SSH 키 값을 복사합니다.
      - "~/.ssh:/root/.ssh"

    working_dir: /mnt/git
    tty: true
