name: Clean Workflow Runs
run-name: 🧹 Clean old workflow runs

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-24.04
    # Only this job has the necessary permissions, following the principle of least privilege
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.1.0
        id: delete
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
