name: Release eip-rotation-handler image and helm chart
run-name: Release eip-rotation-handler image and helm chart ${{ github.ref_name }}

on:
  push:
    tags:
      - 'eip-rotation-handler/[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_NAME: ${{ github.repository_owner }}/eip-rotation-handler

jobs:
  set-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - id: extract
        run: echo "version=${GITHUB_REF_NAME#eip-rotation-handler/}" >> $GITHUB_OUTPUT

  build-container:
    runs-on: ubuntu-24.04
    needs: set-version
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: box/kubernetes/eip-rotation-handler
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
      IMAGE_DESCRIPTION: "AWS EIP rotation handler for Kubernetes"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
          # OCI Image Spec:
          # https://github.com/opencontainers/image-spec/blob/main/annotations.md
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: box/kubernetes/eip-rotation-handler
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
          provenance: false
          sbom: false
          outputs: type=image,name=target

  helm-package:
    runs-on: ubuntu-24.04
    needs: [set-version, build-container]
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: box/kubernetes/eip-rotation-handler
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 3.14.0

      - name: Update Helm chart version
        run: |
          sed -i "s/^version:.*/version: ${VERSION}/" deploy/helm/eip-rotation-handler/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: ${VERSION}/" deploy/helm/eip-rotation-handler/Chart.yaml

      - name: Package Helm chart
        run: |
          helm package deploy/helm/eip-rotation-handler --destination ./charts/
      
      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart-tgz
          path: box/kubernetes/eip-rotation-handler/charts/eip-rotation-handler-${{ env.VERSION }}.tgz
          retention-days: 7

  release:
    runs-on: ubuntu-24.04
    needs: [set-version, build-container, helm-package]
    permissions:
      contents: write
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Helm chart artifact
        uses: actions/download-artifact@v5
        with:
          name: helm-chart-tgz
          path: ./helm-chart

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: eip-rotation-handler ${{ env.VERSION }}
          body: |
            ## Summary

            [eip-rotation-handler](https://github.com/younsl/box/tree/main/box/kubernetes/eip-rotation-handler) is an AWS Elastic IP rotation handler controlled by Kubernetes DaemonSet.

            ## Installation

            eip-rotation-handler helm chart is available on this release page.

            ### Helm Chart

            Download the `eip-rotation-handler-${{ env.VERSION }}.tgz` file from the assets below and install it:

            ```bash
            # Download the chart
            curl -L -o eip-rotation-handler-${{ env.VERSION }}.tgz https://github.com/younsl/box/releases/download/eip-rotation-handler-${{ env.VERSION }}/eip-rotation-handler-${{ env.VERSION }}.tgz

            # Install eip-rotation-handler from downloaded chart
            helm install eip-rotation-handler ./eip-rotation-handler-${{ env.VERSION }}.tgz \
              --namespace eip-rotation-handler \
              --create-namespace
            ```

            List installed releases:

            ```bash
            helm list -n eip-rotation-handler
            ```

            If you want to upgrade existing eip-rotation-handler release, run the following command:

            ```bash
            helm upgrade eip-rotation-handler ./eip-rotation-handler-${{ env.VERSION }}.tgz \
              --namespace eip-rotation-handler \
              --values <YOUR_VALUES_FILE>.yaml
            ```
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./helm-chart/eip-rotation-handler-${{ env.VERSION }}.tgz 